#!/bin/bash
#
# Frappe Quickstart - Zero Configuration Setup
# Purpose: Automated setup and launch of Frappe Docker environment
# Usage: ./start.sh [--preset <name>] [--port <number>] [--no-browser] [--dev] [--help]
#

set -e

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Source library files
source scripts/lib/colors.sh
source scripts/lib/utils.sh
source scripts/lib/validators.sh

# Default values
PRESET="erp"
PORT=""
NO_BROWSER=false
DEV_MODE=false

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --preset)
            PRESET="$2"
            shift 2
            ;;
        --port)
            PORT="$2"
            shift 2
            ;;
        --no-browser)
            NO_BROWSER=true
            shift
            ;;
        --dev)
            DEV_MODE=true
            shift
            ;;
        --help|-h)
            header "Frappe Quickstart - Usage"
            echo ""
            echo "Usage: ./start.sh [OPTIONS]"
            echo ""
            echo "Options:"
            echo "  --preset <name>    Use preset configuration (minimal, erp, education, ecommerce, healthcare)"
            echo "  --port <number>    Force specific port (default: auto-detect from 8080)"
            echo "  --no-browser       Don't open browser automatically"
            echo "  --dev              Use development compose file"
            echo "  --help, -h         Show this help message"
            echo ""
            echo "Examples:"
            echo "  ./start.sh                           # Start with ERP preset"
            echo "  ./start.sh --preset minimal          # Start with minimal Frappe"
            echo "  ./start.sh --preset erp --port 8081  # Start ERP on port 8081"
            echo ""
            exit 0
            ;;
        *)
            error "Unknown option: $1"
            echo "Use --help for usage information"
            exit 1
            ;;
    esac
done

# Display header
clear
print_box "Frappe Quickstart - Setup Wizard"
echo ""
subheader "From zero to Frappe in 3 minutes. No configuration required."
echo ""
separator 60
echo ""

# Validate preset
if ! validate_preset "$PRESET"; then
    error "Invalid preset: $PRESET"
    echo "Valid presets: minimal, erp, education, ecommerce, healthcare"
    exit 1
fi

# Step 1: Check dependencies
step "Checking dependencies..."

# Check Docker
if ! validate_docker; then
    error "Docker is not installed or not running"
    echo ""
    echo "Please install Docker first:"
    echo "  • Linux: https://docs.docker.com/engine/install/"
    echo "  • macOS: https://docs.docker.com/desktop/install/mac-install/"
    echo "  • Windows: https://docs.docker.com/desktop/install/windows-install/"
    echo ""
    exit 1
fi
success "Docker found ($(docker --version | cut -d' ' -f3 | tr -d ','))"

# Check Docker Compose
if ! validate_docker_compose; then
    error "Docker Compose is not installed"
    echo ""
    echo "Please install Docker Compose:"
    echo "  https://docs.docker.com/compose/install/"
    echo ""
    exit 1
fi
COMPOSE_CMD=$(get_compose_cmd)
success "Docker Compose found ($(${COMPOSE_CMD} version --short 2>/dev/null || echo 'installed'))"

# Check jq
if ! command_exists jq; then
    warning "jq not found, installing may improve experience"
    warning "Install: sudo apt-get install jq (Linux) or brew install jq (macOS)"
else
    success "jq found"
fi

# Check base64
if ! command_exists base64; then
    error "base64 command not found (should be available by default)"
    exit 1
fi
success "base64 found"

echo ""

# Step 2: Check ports
step "Checking ports..."

if [ -n "$PORT" ]; then
    # User specified port
    if ! validate_port "$PORT"; then
        error "Invalid port number: $PORT"
        exit 1
    fi

    if ! is_port_available "$PORT"; then
        error "Port $PORT is already in use"
        PORT=$(find_available_port 8080)
        warning "Using alternative port: $PORT"
    else
        success "Port $PORT is available"
    fi
else
    # Auto-detect port
    PORT=$(find_available_port 8080)
    success "Port $PORT is available"
fi

echo ""

# Step 3: Generate passwords
step "Generating secure passwords..."

ADMIN_PASSWORD=$(generate_password 16)
DB_ROOT_PASSWORD=$(generate_password 16)

success "Admin password generated"
success "Database password generated"

echo ""

# Step 4: Create configuration
step "Creating configuration..."

# Copy .env.example to .env
cat > .env << EOF
# Frappe Configuration
FRAPPE_VERSION=version-15
SITE_NAME=frontend

# Security - Auto-generated by start.sh
ADMIN_PASSWORD=${ADMIN_PASSWORD}
DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}

# Network Configuration
PORT=${PORT}

# Docker Configuration
PROJECT_NAME=frappe_quickstart
IMAGE_NAME=frappe_quickstart:latest

# Preset used
PRESET=${PRESET}
EOF

success ".env file created"

# Create apps.json from preset
if [ -f "presets/${PRESET}.json" ]; then
    cp "presets/${PRESET}.json" apps.json
    success "apps.json created from ${PRESET} preset"
else
    error "Preset file not found: presets/${PRESET}.json"
    exit 1
fi

echo ""

# Step 5: Build Docker image
step "Building Docker image..."
echo ""

# Encode apps.json to base64
APPS_JSON_BASE64=$(base64 -w 0 apps.json 2>/dev/null || base64 apps.json)

info "Building frappe_quickstart:latest (this may take 5-10 minutes on first run)"
echo ""

# Build with progress
if docker build \
    --build-arg APPS_JSON_BASE64="${APPS_JSON_BASE64}" \
    --build-arg FRAPPE_BRANCH=version-15 \
    -t frappe_quickstart:latest \
    -f Dockerfile \
    . ; then
    echo ""
    success "Build complete"
else
    echo ""
    error "Build failed"
    echo ""
    echo "Check the error messages above for details."
    echo "Common issues:"
    echo "  • Network connectivity problems"
    echo "  • Insufficient disk space"
    echo "  • Invalid apps.json configuration"
    echo ""
    exit 1
fi

echo ""

# Step 6: Start services
step "Starting services..."
echo ""

# Stop any existing services
${COMPOSE_CMD} down &> /dev/null || true

# Determine compose files
COMPOSE_FILES="-f docker-compose.yml"
if [ "$DEV_MODE" = true ] && [ -f "docker-compose.dev.yml" ]; then
    COMPOSE_FILES="${COMPOSE_FILES} -f docker-compose.dev.yml"
fi

# Start services
info "Starting Docker Compose services..."
${COMPOSE_CMD} ${COMPOSE_FILES} up -d

echo ""
success "Services started"

echo ""

# Step 7: Wait for services
step "Waiting for services to be healthy..."
echo ""

info "This may take 2-3 minutes while the site is being created..."
echo ""

# Wait for create-site to complete
WAIT_TIME=0
MAX_WAIT=300  # 5 minutes

while [ $WAIT_TIME -lt $MAX_WAIT ]; do
    # Check if create-site container has completed
    if ${COMPOSE_CMD} ps create-site 2>/dev/null | grep -q "exited (0)"; then
        break
    fi

    # Check if it failed
    if ${COMPOSE_CMD} ps create-site 2>/dev/null | grep -q "exited ([^0])"; then
        error "Site creation failed"
        echo ""
        echo "Container logs:"
        ${COMPOSE_CMD} logs create-site
        exit 1
    fi

    sleep 5
    WAIT_TIME=$((WAIT_TIME + 5))

    # Show progress
    if [ $((WAIT_TIME % 15)) -eq 0 ]; then
        info "Still waiting... ($WAIT_TIME seconds elapsed)"
    fi
done

if [ $WAIT_TIME -ge $MAX_WAIT ]; then
    error "Timeout waiting for services"
    echo ""
    echo "Services status:"
    ${COMPOSE_CMD} ps
    echo ""
    echo "Check logs with: ${COMPOSE_CMD} logs"
    exit 1
fi

echo ""
success "All services healthy"

echo ""

# Step 8: Open browser
if [ "$NO_BROWSER" = false ]; then
    step "Opening browser..."
    sleep 2
    open_browser "http://localhost:${PORT}"
    success "Browser opened"
    echo ""
fi

# Step 9: Display completion message
print_box "Setup Complete!"
echo ""

success "Your Frappe site is ready!"
echo ""
header "Access Information:"
echo ""
echo "  ${COLOR_BOLD}URL:${COLOR_RESET}      http://localhost:${PORT}"
echo "  ${COLOR_BOLD}Username:${COLOR_RESET} Administrator"
echo "  ${COLOR_BOLD}Password:${COLOR_RESET} ${ADMIN_PASSWORD}"
echo ""
separator 60
echo ""
header "Next Steps:"
echo ""
echo "  • Run ${COLOR_CYAN}./frappe-cli${COLOR_RESET} for interactive menu"
echo "  • Run ${COLOR_CYAN}./frappe-cli domain${COLOR_RESET} to setup public access"
echo "  • Run ${COLOR_CYAN}./frappe-cli apps${COLOR_RESET} to install more apps"
echo ""
header "Documentation:"
echo ""
echo "  • Quick Start:      ${COLOR_DIM}docs/quickstart.md${COLOR_RESET}"
echo "  • Commands:         ${COLOR_DIM}docs/commands.md${COLOR_RESET}"
echo "  • Troubleshooting:  ${COLOR_DIM}docs/troubleshooting.md${COLOR_RESET}"
echo ""
separator 60
echo ""

subheader "Tip: Save your password somewhere safe!"
echo ""
